# GPU MachineSet Parameters for AWS g6.4xlarge
# Edit these values to customize your GPU nodes

# Instance configuration
instanceType: g6.4xlarge         # NVIDIA L4 GPU
replicas: 1                      # Number of GPU nodes

# GPU details for this instance type:
# - 1x NVIDIA L4 (24GB GDDR6)
# - 16 vCPUs
# - 64 GB RAM
# - Cost: ~$2.15/hour (on-demand, us-east-1)
# - Good for: Large models, vision models, high throughput
