apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-info-discovery
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: cluster-info-discovery
      restartPolicy: OnFailure
      containers:
      - name: discover
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          set -e
          
          echo "Discovering cluster information..."
          
          # Get cluster information
          CLUSTER_NAME=$(oc get infrastructure cluster -o jsonpath='{.status.infrastructureName}')
          REGION=$(oc get infrastructure cluster -o jsonpath='{.status.platformStatus.aws.region}')
          
          # Try to get availability zone from worker machines first, fallback to master machines
          AVAILABILITY_ZONE=$(oc get machines -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=worker -o jsonpath='{.items[0].spec.providerSpec.value.placement.availabilityZone}' 2>/dev/null || true)
          if [ -z "$AVAILABILITY_ZONE" ]; then
            echo "  No worker machines found, using master node configuration..."
            AVAILABILITY_ZONE=$(oc get machines -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=master -o jsonpath='{.items[0].spec.providerSpec.value.placement.availabilityZone}')
          fi
          
          INFRA_ID=$(oc get infrastructure cluster -o jsonpath='{.status.infrastructureName}')
          
          # Try to get AMI from existing machinesets, fallback to machines
          AMI_ID=$(oc get machineset -n openshift-machine-api -o json 2>/dev/null | jq -r '.items[] | select(.metadata.name | contains("gpu") | not) | .spec.template.spec.providerSpec.value.ami.id' | head -1 || true)
          if [ -z "$AMI_ID" ]; then
            echo "  No machinesets found, using machine AMI configuration..."
            AMI_ID=$(oc get machines -n openshift-machine-api -o jsonpath='{.items[0].spec.providerSpec.value.ami.id}')
          fi
          
          echo "  Cluster Name: $CLUSTER_NAME"
          echo "  Region: $REGION"
          echo "  Availability Zone: $AVAILABILITY_ZONE"
          echo "  Infrastructure ID: $INFRA_ID"
          echo "  AMI ID: $AMI_ID"
          
          # Validate cluster info
          if [ -z "$CLUSTER_NAME" ] || [ -z "$REGION" ] || [ -z "$AVAILABILITY_ZONE" ] || [ -z "$AMI_ID" ]; then
            echo "Error: Failed to retrieve cluster information"
            exit 1
          fi
          
          # Create ConfigMap with discovered values
          cat <<EOF | oc apply -f -
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: cluster-info
            namespace: openshift-machine-api
          data:
            clusterName: "$CLUSTER_NAME"
            region: "$REGION"
            availabilityZone: "$AVAILABILITY_ZONE"
            infraID: "$INFRA_ID"
            amiId: "$AMI_ID"
          EOF
          
          echo "Cluster information ConfigMap created successfully"
