apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-info-writer
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
