apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-info-discovery
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-info-writer
subjects:
  - kind: ServiceAccount
    name: cluster-info-discovery
    namespace: openshift-machine-api
